### ISSUE TITLE
Create homepage view

### ISSUE THREAD

**Issue by sophiapenate** [sophiabarrett/technically-a-blog#6]
![Screen Shot 2021-12-11 at 3 51 21 PM](https://user-images.githubusercontent.com/89703721/145693978-c542aaf4-d65e-4dac-ae76-d6780a7565e5.png)

**Comment by sophiabarrett** [comment]
Header nav should display login or login depending on current session status

**Comment by sophiapenate** [comment]
Pushed to develop
